[profile.default]
  libs = ['node_modules', 'lib']
  out = "out"
  src = "src"
  ffi = true
  fuzz = { runs = 1000 }
  evm_version = 'cancun'
  optimizer = true
  optimizer_runs = 200
  solc_version = '0.8.28'

  remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "risc0/=lib/risc0-ethereum/contracts/src/",
    "forge-std/=lib/forge-std/src/"
  ]

  # forge-deploy
  fs_permissions = [
    { access = "read-write", path = "./deployments" },
    { access = "read", path = "./out" },
    { access = "read", path = "./deployment-config.json" },
    { access = "read", path = "./deployment-config-updated.json" },
    { access = "read", path = "./deployment-config-release.json" },
    { access = "read", path = "./deployment-config-testnet.json" },
    { access = "read", path = "./deployment-config.sepolia.json" },
    { access = "read", path = "./deployment-config.op.json" },
    { access = "read", path = "./deployment-config.linea.json" },
    { access = "read", path = "./deployment-rebalancer-config.json" },
    { access = "read-write", path = "./test/" },
    { access = "read-write", path = "./script/deployment/mainnet/output/" }
]

[profile.testnet]
  evm_version = 'paris' # Because Linea Sepolia is on Paris
  optimizer = true
  optimizer_runs = 180

[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 3 # outputs stack trace for failed tests only (https://book.getfoundry.sh/reference/config/testing)

[lint]
  exclude_lints = ["asm-keccak256","unwrapped-modifier-logic","pascal-case-struct","mixed-case-function","unsafe-typecast","unsafe-cheatcode","mixed-case-variable"] # possibly reintroduce mixed-case-variable later
  ignore = ["test/**/*", "script/**/*"]

[rpc_endpoints]
  # Mainnet
  linea = "${LINEA_RPC_URL}"
  mainnet = "${MAINNET_RPC_URL}"
  optimism = "${OPTIMISM_RPC_URL}"
  base = "${BASE_RPC_URL}"

  # Testnet
  linea_sepolia = "${LINEA_SEPOLIA_RPC_URL}"
  sepolia = "${SEPOLIA_RPC_URL}"
  op_sepolia = "${OPTIMISM_SEPOLIA_RPC_URL}"
  base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
  anvil1 = "http://localhost:8545"
  anvil2 = "http://localhost:8546"

[etherscan]
  # Mainnet
  linea = { chain = 59144, key = "${ETHERSCAN_API_KEY}" }
  mainnet = { chain = 1, key = "${ETHERSCAN_API_KEY}" }
  optimism = { chain = 10, key = "${ETHERSCAN_API_KEY}" }
  base = { chain = 8453, key = "${ETHERSCAN_API_KEY}" }
  
  # Testnet
  linea_sepolia = { chain = 59141, key = "${ETHERSCAN_API_KEY}" }
  sepolia = { chain = 11155111, key = "${ETHERSCAN_API_KEY}" }
  op_sepolia = { chain = 11155420, key = "${ETHERSCAN_API_KEY}" }
  base_sepolia = { chain = 84532, key = "${ETHERSCAN_API_KEY}" }